# Generated by Django 5.2 on 2025-07-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_remove_servicio_hora_servicio_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('Manicure', 'Manicure'), ('Pedicure', 'Pedicure'), ('Retiros', 'Retiros')], default='Manicure', max_length=40),
        ),
    ]
